from random import randint
import smtplib

def initialize():
    server = smtplib.SMTP('smtp.gmail.com:587')
    server.ehlo()
    server.starttls()
    print("[username]@gmail.com")
    username = input("Username: ")
    username = username.strip() + '@gmail.com'
    password = input("Password: ")
    server.login(username,password)
    return username, server

def santa(sheetname): #.tsv plz
    sheet = open(sheetname)
    give = []
    receive = []

    final = []
    sheet.readline()
    for line in sheet:
        trimmed = tuple(line.strip().split('\t')[1:4])
        give.append(trimmed)
        receive.append(trimmed)

    #print(receive)

    for i in range(len(give)):
        if len(give) == 1:
            if give[0][1] == receive[0][1]:
                print("Edgecase")
                raise # Not necessary but to be safe
                old = final[0]
                name = give[0][0].split(' ')[0]
                new = (name, give[0][1],receive[0],receive[2])
                swapped1 = (old[0],old[1],new[2],new[3])
                swapped2 = (new[0],new[1],old[2],new[3])
                final.pop(0)
                final.append(swapped1,swapped2)
            else:
                name = give[0][0].split(' ')[0]
                final.append((name, give[0][1],receive[0][0],receive[0][2]))
                give.pop(0)
                receive.pop(0)
            break
        proper = False
        while not proper:
            r = randint(0,len(receive)-1)
            #print("Length:"+str(len(receive)))
            #print("r:"+str(r))
            if give[0][1] != receive[r][1]:
                proper = True
                name = give[0][0].split(' ')[0]
                final.append((name, give[0][1],receive[r][0],receive[r][2]))
                give.pop(0)
                receive.pop(r)
    return final

def email_santa(username, server, santa_list):
    FROM = username
    for element in santa_list:
        TO = [element[1]]

        msg = '\r\n'.join([
                "From: "+FROM,
                "To: "+", ".join(TO),
                "Subject: Secret Santa Assignment",
                "",
"""Hey {},

Thanks for participating in Secret Santa! You've been assigned {} to give a gift to.

Details they wished to share:
"{}"

Remember that the gift exchange will occur on December 14th (around 12:30pm), and that max gift cost is $15.

Thanks again, and good luck with exams!

Emerson

(P.S. This email was autogenerated, if you have any concerns please let me know!)
""".format(element[0],element[2],element[3])
                ])
        try:
            server.sendmail(FROM, TO, msg)
        except Exception as e:
            print("Error")
            print(e)
            print("msg")
            print(str(msg))
    server.close()
    print("Emails sent")

if __name__ == '__main__':
    username, server = initialize()
    santa_list = santa("santa.tsv") #Ensure ascii-compliant symbols!
    email_santa(username, server, santa_list)
